// noinspection JSUnusedGlobalSymbols

export enum ZoomErrors {
    ZOOM_400_EMPTY_MEETING_NUMBER = "ZOOM_400_EMPTY_MEETING_NUMBER",
    ZOOM_400_EMPTY_ROLE = "ZOOM_400_EMPTY_ROLE",
    ZOOM_400_INVALID_ROLE = "ZOOM_400_INVALID_ROLE",
    ZOOM_401_UNAUTHORIZED = "ZOOM_401_UNAUTHORIZED",
}
